name: Lint Go Code

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@master
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.27
          github-token: ${{ secrets.github_token }}